version: "3"
services:

  emprestimo-service-db:
    container_name: emprestimo-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - nossagrana

  emprestimo-service:
    container_name: emprestimo-service
    image: brunovieirafarias/microservico-emprestimo
    depends_on:
      - emprestimo-service-db
    restart: always
    ports:
      - "8081:8081"
    environment: 
      EMPRESTIMO_DB_HOST: emprestimo-service-db
      EMPRESTIMO_DB_PORT: 27017
      USUARIO_SERVICE_HOST: usuario-service
      USUARIO_SERVICE_PORT: 8085    
    networks:
      - nossagrana

  usuario-service:
    container_name: usuario-service
    image: brunovieirafarias/microservico-usuario
    depends_on:
      - usuario-service-db
    restart: always
    ports:
      - "8085:8085"
    networks:
      - nossagrana

  nossagrana-ui:
    container_name: nossagrana-ui
    image: diegoclimaites/nossagrana-frontend
    depends_on:
      - usuario-service-db
    restart: always
    ports:
      - "8083:80"
    networks:
      - nossagrana

  emailsender-service:
    container_name: emailsender-service
    image: brunovieirafarias/microservico-emailsender
    restart: always
    ports:
      - "8082:8082"
    networks:
      - nossagrana
 
networks:
  nossagrana:        