version: "3"
services:
  emprestimo-service:
    container_name: emprestimo-service
    build:
      context: ./emprestimo
      dockerfile: Dockerfile
    image: emprestimo
    restart: always
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "8081:8081"
    networks:
      - nossagrana
  emprestimo-service-db:
    container_name: emprestimo-db
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    networks:
      - nossagrana

networks:
  nossagrana: