version: "3"
services:

  visualizador: 
    image: dockersamples/visualizer 
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock" 
    ports: 
      - 8080:8080 
    deploy: 
      placement: 
        constraints: 
          - node.role == manager 

  emprestimo-service-db:    
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    restart: always
    ports:
      - "27017:27017"
    networks:
      - nossagrana

  emprestimo-service:
    image: brunovieirafarias/microservico-emprestimo
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - emprestimo-service-db
    restart: always
    ports:
      - "8081:8081"
    environment: 
      EMPRESTIMO_DB_HOST: emprestimo-service-db
      EMPRESTIMO_DB_PORT: 27017
      USUARIO_SERVICE_HOST: usuario-service
      USUARIO_SERVICE_PORT: 8085    
    networks:
      - nossagrana

  usuario-service-db:
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: mongod --port 27018
    restart: always
    ports:
      - "27018:27018"
    networks:
      - nossagrana

  usuario-service:
    image: brunovieirafarias/microservico-usuario
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - usuario-service-db
    restart: always
    ports:
      - "8085:8085"
    environment: 
      USUARIO_DB_HOST: usuario-service-db
      USUARIO_DB_PORT: 27018
    networks:
      - nossagrana

  nossagrana-ui:
    image: diegoclimaites/nossagrana-frontend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - usuario-service
      - emprestimo-service
    restart: always
    ports:
      - "8083:80"
    networks:
      - nossagrana

  emailsender-service:
    image: brunovieirafarias/microservico-emailsender
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    restart: always
    ports:
      - "8082:8082"
    networks:
      - nossagrana
 
networks:
  nossagrana:    
    external: true
